export default {
    id: 7,
    name: "Basket",
    tiles: [
        [
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "goal", team: 1 },
            { type: "goal", team: 1 },
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "goal", team: 1 },
            { type: "goal", team: 1 },
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            { type: "block" },
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            { type: "block" },
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "warp" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "warp", v: true, x: 9, y: 0 },
        ],
        [
            { type: "warp" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "warp", v: true, x: 10, y: 0 },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            { type: "block" },
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            { type: "block" },
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "goal", team: 2 },
            { type: "goal", team: 2 },
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "goal", team: 2 },
            { type: "goal", team: 2 },
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
        ],
    ],
    ballSpawns: [
        { x: 10, y: 5 },
        { x: 10, y: 20 },
    ],
    playerSpawn: { x: 10, y: 11 },
}
