export default {
    id: 2,
    name: "Lobby",
    tiles: [
        [
            { type: "block" },
            { type: "warp", h: true, x: 14, y: 7 },
            { type: "warp", h: true, x: 14, y: 8 },
            { type: "block" },
            { type: "goal", team: 1 },
            { type: "goal", team: 1 },
            { type: "block" },
            { type: "warp", h: true, x: 14, y: 1 },
            { type: "warp", h: true, x: 14, y: 2 },
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            { type: "warp", h: true, x: 0, y: 7 },
            { type: "warp", h: true, x: 0, y: 8 },
            { type: "block" },
            { type: "goal", team: 2 },
            { type: "goal", team: 2 },
            { type: "block" },
            { type: "warp", h: true, x: 0, y: 1 },
            { type: "warp", h: true, x: 0, y: 2 },
            { type: "block" },
        ],
    ],
    ballSpawns: [{ x: 7.5, y: 2 }],
    playerSpawn: { x: 7.5, y: 8 },
}
