export default {
    id: 454,
    name: "Maitrise",
    tiles: [
        [
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
        ],
        [
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "warp", h: true, x: 20, y: 4 },
            { type: "warp", h: true, x: 20, y: 5 },
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            { type: "goal", team: 1 },
            { type: "goal", team: 1 },
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            { type: "goal", team: 1 },
            { type: "goal", team: 1 },
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "warp" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "warp", v: true, x: 10, y: 0 },
        ],
        [
            { type: "warp" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "warp", v: true, x: 11, y: 0 },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            { type: "goal", team: 2 },
            { type: "goal", team: 2 },
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            { type: "goal", team: 2 },
            { type: "goal", team: 2 },
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "warp", h: true, x: 1, y: 4 },
            { type: "warp", h: true, x: 1, y: 5 },
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
        ],
    ],
    ballSpawns: [
        { x: 11, y: 2 },
        { x: 11, y: 20 },
    ],
    playerSpawn: { x: 11, y: 17 },
}
