export default {
    id: 1,
    name: "Temple du Ballon",
    tiles: [
        [
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "goal", team: 1 },
            { type: "goal", team: 1 },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
        ],
        [
            { type: "warp", v: true },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            { type: "goal", team: 1 },
            { type: "goal", team: 1 },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "warp", v: true, x: 1, y: 0 },
        ],
        [
            { type: "warp", v: true },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "warp", v: true, x: 2, y: 0 },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            { type: "block" },
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            { type: "block" },
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            { type: "block" },
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            { type: "block" },
            { type: "block" },
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            { type: "block" },
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            { type: "block" },
            { type: "block" },
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            { type: "block" },
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            { type: "block" },
            { type: "block" },
        ],
        [
            { type: "warp", v: true },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "warp", v: true, x: 17, y: 0 },
        ],
        [
            { type: "warp", v: true },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            { type: "goal", team: 2 },
            { type: "goal", team: 2 },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "warp", v: true, x: 18, y: 0 },
        ],
        [
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "goal", team: 2 },
            { type: "goal", team: 2 },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
        ],
    ],
    ballSpawns: [
        { x: 10, y: 2 },
        { x: 10, y: 20 },
    ],
    playerSpawn: { x: 10, y: 14 },
}
