export default {
    tiles: [
        [
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "warp", x: 19, y: 7, h: true },
            { type: "warp", x: 19, y: 8, h: true },
            { type: "block" },
            { type: "goal", team: 1 },
            { type: "goal", team: 1 },
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
        ],
        [
            { type: "warp" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "warp", x: 1, y: 0, v: true },
        ],
        [
            { type: "warp" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "warp", x: 2, y: 0, v: true },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "warp" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "warp", x: 17, y: 0, v: true },
        ],
        [
            { type: "warp" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "warp", x: 18, y: 0, v: true },
        ],
        [
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "warp", x: 0, y: 7, h: true },
            { type: "warp", x: 0, y: 8, h: true },
            { type: "block" },
            { type: "goal", team: 2 },
            { type: "goal", team: 2 },
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
        ],
    ],
    ballSpawns: [{ x: 10, y: 2 }],
    playerSpawn: { x: 10, y: 17 },
    name: "Temple Aérien",
    id: 685454,
}
