export default {
    id: 3454,
    name: "Tiny",
    tiles: [
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            { type: "goal", team: 2 },
            { type: "goal", team: 2 },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
        ],
        [
            { type: "warp" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "warp", v: true, x: 1, y: 0 },
        ],
        [
            { type: "warp" },
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "warp", v: true, x: 2, y: 0 },
        ],
        [
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "block" },
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
        ],
        [
            { type: "warp" },
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "warp", v: true, x: 13, y: 0 },
        ],
        [
            { type: "warp" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            {},
            {},
            { type: "warp", v: true, x: 14, y: 0 },
        ],
        [
            { type: "block" },
            {},
            {},
            {},
            {},
            {},
            { type: "block" },
            { type: "goal", team: 1 },
            { type: "goal", team: 1 },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
            { type: "block" },
        ],
    ],
    ballSpawns: [
        { x: 8, y: 2 },
        { x: 8, y: 14 },
    ],
    playerSpawn: { x: 8, y: 11 },
}
